spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/musculashz
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=data
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.threads.virtual.enabled=true

server.servlet.context-path=/api/
